#!/bin/sh

CONF_FILE="etc/system.conf"

YI_HACK_PREFIX="/home/yi-hack"

get_config()
{
	key=$1
	grep $1 $YI_HACK_PREFIX/$CONF_FILE | cut -d "=" -f2
}
                
if [[ $(get_config PROXYCHAINSNG) == "yes" ]] ; then
	$YI_HACK_PREFIX/bin/proxychains4 ./cloudAPI_real "$@"
else
	./cloudAPI_real "$@"
fi
